name: sahariano_travel
description: A new Flutter project.
publish_to: 'none'
version: 1.1.5+4194412

environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_verification_code: ^1.1.6
  package_info_plus: ^1.0.1
  international_phone_input: ^1.0.4
  smooth_page_indicator: ^1.0.0+2
  firebase_auth: ^4.1.1
  pinput: ^2.2.16
  device_info_plus: ^4.0.0
  shared_preferences: ^2.0.12
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  firebase_messaging: ^14.0.4
  cloud_firestore: ^4.0.4 
  firebase_storage: 
  http: ^0.13.4
  dio: ^4.0.4
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+5
  image_cropper: ^3.0.1
  buildcondition: ^0.0.4
  flutter_zoom_drawer: ^2.3.1
  restart_app: ^1.1.0
  webview_flutter: ^3.0.0
  showcaseview: ^2.0.0+1
  shimmer: ^2.0.0
  country_list_pick: ^1.0.1+5
  awesome_dialog: ^3.0.2
  pdf: ^3.7.4
  open_file: ^3.1.0
  path_provider: ^2.0.1
  html: ^0.15.0
  font_awesome_flutter: ^10.1.0
  flutter_local_notifications:
  firebase_remote_config: ^3.0.4
  jiffy: ^5.0.0
  new_version: ^0.3.1
  url_launcher: ^6.1.4
  flutter_share: ^2.0.0
  lottie: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.4  
  change_app_package_name: ^1.1.0
flutter_native_splash:
  image: assets/logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/en.json
    - assets/lang/ar.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
